{% set name = "discid" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/discid-{{ version }}.tar.gz
  sha256: 7160a1211ac3d6a6d8213fb88dd3d73e32abe5e01336a5a4c985b082a97d4335

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - libdiscid

test:
  imports:
    - discid
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://python-discid.readthedocs.org/
  dev_url: https://github.com/JonnyJD/python-discid
  summary: Python binding of Libdiscid
  license: LGPL-3.0-or-later AND GPL-3.0-or-later
  license_file:
    - COPYING.LESSER
    - COPYING

extra:
  recipe-maintainers:
    - HeavyTony2
